// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// frags2counts
List frags2counts(NumericVector nfmid, NumericVector tfmid, NumericVector rstart, NumericVector rend);
RcppExport SEXP seqDNAcopy_frags2counts(SEXP nfmidSEXP, SEXP tfmidSEXP, SEXP rstartSEXP, SEXP rendSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type nfmid(nfmidSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tfmid(tfmidSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rstart(rstartSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rend(rendSEXP);
    __result = Rcpp::wrap(frags2counts(nfmid, tfmid, rstart, rend));
    return __result;
END_RCPP
}
